//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityMVCProject.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Departmans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departmans()
        {
            this.Lecturers = new HashSet<Lecturers>();
            this.Students = new HashSet<Students>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage ="DepartmanName boþ geçilemez")]
        public string DepartmanName { get; set; }
        [Required(ErrorMessage = "Address boþ geçilemez")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Telephone boþ geçilemez")]
        public Nullable<long> Telephone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lecturers> Lecturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Students> Students { get; set; }
    }
}
