//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityMVCProject.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Lecturers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lecturers()
        {
            this.Lessons = new HashSet<Lessons>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage ="FirstName zorunlu")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "LastName zorunlu")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Email zorunlu")]
         public string Email { get; set; }
        [Required(ErrorMessage = "Age zorunlu")]
        [Range(24,65)]
        public Nullable<int> Age { get; set; }
        [Display(Name ="Departman Name")]
        [Required(ErrorMessage = "DepartmanId zorunlu")]
        public Nullable<int> DepartmanId { get; set; }
    
        public virtual Departmans Departmans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lessons> Lessons { get; set; }
    }
}
