//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityMVCProject.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Lessons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lessons()
        {
            this.Notes = new HashSet<Notes>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "LessonName boþ geçilemez")]
        public string LessonName { get; set; }
        [Display(Name ="StudentName")]
        [Required(ErrorMessage = "StudentName boþ geçilemez")]
        public Nullable<int> StudentId { get; set; }
        [Required(ErrorMessage = "Credit boþ geçilemez")]
        public Nullable<int> Credit { get; set; }
        [Required(ErrorMessage = "DepartmanName boþ geçilemez")]
        public Nullable<int> LecturerId { get; set; }
    
        public virtual Lecturers Lecturers { get; set; }
        public virtual Students Students { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notes> Notes { get; set; }
    }
}
