//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityMVCProject.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        public int Id { get; set; }
        public Nullable<int> LessonId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> Vize { get; set; }
        public Nullable<int> Final { get; set; }
        public Nullable<double> Average { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Lessons Lessons { get; set; }
        public virtual Students Students { get; set; }
    }
}
