//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityMVCProject.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students()
        {
            this.Lessons = new HashSet<Lessons>();
            this.Notes = new HashSet<Notes>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "FirstName boþ geçilemez")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "LastName boþ geçilemez")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "StudentNo boþ geçilemez")]
        public string StudentNo { get; set; }
        [Display(Name ="DepartmanName")]
        [Required(ErrorMessage = "DepartmanName boþ geçilemez")]
        public Nullable<int> DepartmanId { get; set; }
        [Required(ErrorMessage = "Vize boþ geçilemez")]
       [Range(18,34)]
        public Nullable<int> Age { get; set; }
    
        public virtual Departmans Departmans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lessons> Lessons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notes> Notes { get; set; }
    }
}
